# Generated by Django 2.2.1 on 2019-08-22 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imei', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Devices',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='juan_8356_2019_07_03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.CharField(max_length=100)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Altitude', models.IntegerField()),
                ('Distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Device')),
            ],
        ),
    ]
