# Generated by Django 2.2.1 on 2019-08-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20190822_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ana_0684_2019_07_17',
        ),
        migrations.DeleteModel(
            name='ana_0684_2019_07_18',
        ),
        migrations.DeleteModel(
            name='ana_0684_2019_07_19',
        ),
        migrations.DeleteModel(
            name='juan_8356_2019_07_03',
        ),
        migrations.DeleteModel(
            name='juan_8356_2019_07_05',
        ),
        migrations.DeleteModel(
            name='juan_8356_2019_07_06',
        ),
        migrations.DeleteModel(
            name='juan_8356_2019_07_09',
        ),
        migrations.DeleteModel(
            name='juan_9012_2019_07_13',
        ),
        migrations.DeleteModel(
            name='juan_9012_2019_07_16',
        ),
        migrations.DeleteModel(
            name='superlimpio_6468_2019_07_29',
        ),
        migrations.DeleteModel(
            name='superlimpio_6468_2019_07_30',
        ),
        migrations.DeleteModel(
            name='superlimpio_6468_2019_07_31',
        ),
        migrations.DeleteModel(
            name='ventasexpres_1847_2019_07_20',
        ),
        migrations.DeleteModel(
            name='ventasexpres_1847_2019_07_22',
        ),
        migrations.DeleteModel(
            name='ventasexpres_1847_2019_07_23',
        ),
        migrations.DeleteModel(
            name='ventasexpres_9656_2019_07_24',
        ),
        migrations.DeleteModel(
            name='ventasexpres_9656_2019_07_25',
        ),
    ]
