# Generated by Django 2.2.1 on 2019-09-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_ana_0684_2019_07_17_ana_0684_2019_07_18_ana_0684_2019_07_19_juan_8356_2019_07_03_juan_8356_2019_07_0'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
