# Generated by Django 2.2.1 on 2019-09-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0011_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMEI', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Devices',
                'ordering': ('id',),
            },
        ),
    ]
