# Generated by Django 2.2.1 on 2019-09-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0012_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Juan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Katy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Superlimpio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ventasexpres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
            ],
        ),
    ]
