# Generated by Django 2.2.1 on 2019-09-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_ana_juan_katy_superlimpio_ventasexpres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ana',
        ),
        migrations.DeleteModel(
            name='Juan',
        ),
        migrations.DeleteModel(
            name='Katy',
        ),
        migrations.DeleteModel(
            name='Superlimpio',
        ),
        migrations.DeleteModel(
            name='Ventasexpres',
        ),
    ]
