# Generated by Django 2.2.1 on 2019-09-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0014_auto_20190912_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventasexpres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
                ('IMEI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Superlimpio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
                ('IMEI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Katy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
                ('IMEI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Juan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
                ('IMEI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Ana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
                ('IMEI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Device')),
            ],
        ),
    ]
