# Generated by Django 2.2.1 on 2019-09-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0015_ana_juan_katy_superlimpio_ventasexpres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juan',
            name='IMEI',
        ),
        migrations.RemoveField(
            model_name='katy',
            name='IMEI',
        ),
        migrations.RemoveField(
            model_name='superlimpio',
            name='IMEI',
        ),
        migrations.RemoveField(
            model_name='ventasexpres',
            name='IMEI',
        ),
        migrations.DeleteModel(
            name='Ana',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Juan',
        ),
        migrations.DeleteModel(
            name='Katy',
        ),
        migrations.DeleteModel(
            name='Superlimpio',
        ),
        migrations.DeleteModel(
            name='Ventasexpres',
        ),
    ]
